modLoader = "javafml"
loaderVersion = "[36,)"
issueTrackerURL = "https://github.com/ValkyrienSkies/Valkyrien-Skies-2/issues"
license = "Apache-2.0"

[[mods]]
modId = "vi"
version = "${version}"
displayName = "Valkyrien Isles"
authors = ["Tri0de", "ewoudje", "VS2 Discord Artists", "TechTastic"]
description = '''
Floating Islands with Valkyrien Skies physics
'''
logoFile = "icon.png"

[[dependencies.vi]]
modId = "forge"
mandatory = false
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vi]]
modId = "valkyrienskies"
mandatory = false
versionRange = "[1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vi]]
modId = "minecraft"
mandatory = false
versionRange = "[1.16.5,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vi]]
modId = "minecraft"
mandatory = false
versionRange = "[1.16.5,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vi]]
modId = "architectury"
mandatory = false
versionRange = "[1.31.61,)"
ordering = "AFTER"
side = "BOTH"